- command:
   name: runtests
   execute:
      - cd tests/driver
      - ./test_runner
   description: Run Yass unit tests
- command:
   name: debug
   execute:
      - gprbuild -P yass.gpr
   description: Build Yass in debug mode
- command:
   name: release
   execute:
      - tclsh others/build.tcl
   description: Build yass in release mode
- command:
   name: analyze
   execute:
      - gprbuild -P yass.gpr -XMode=analyze
   description: Build yass in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P yass.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P yass.gpr
   description: Regenerate unit tests
- command:
   name: docs
   execute:
      - others/generatedocs.tcl
   description: Generate code documentation
- command:
   name: gprof
   execute:
      - gprof bin/yass gmon.out
   description: Generate gprof report
- command:
   name: push
   execute:
      - fossil push
      - fossil git export --force
   description: Update remote Fossil repository and its Git mirror
- command:
   name: windows
   execute:
      - sudo docker run --rm -w /app -v $1:/app ghcr.io/thindil/adabuildwin64 /bin/bash others/build.tcl x86_64-windows
   description: Build yass release for Windows on Linux, required argument is full path to the program source code
   flags:
      - unixonly
- command:
   name: tests
   execute:
      - tclsh others/tests.tcl
   description: Build and run yass unit tests
- command:
   name: pretty
   execute:
      - gnatpp -P yass.gpr
   description: Pretty print yass source code
- command:
   name: prettytests
   execute:
      - gnatpp -P tests/prettytests.gpr
   description: Pretty print unit tests source code
- command:
   name: check
   execute:
      - gprclean -P yass.gpr
      - cd obj
      - adactl -f ../others/rules.aru -p ../yass.gpr -o ../adacontrol.log -r yass-aws-templates_parser-dom-unicode-input_sources
   description: Run AdaControl to check correctness of the code
   flags:
      - unixpath
- command:
   name: checkall
   execute:
      - bob debug
      - bob tests
      - bob check
   description: Run all the project tests
- command:
   name: checkfile
   execute:
      - gprclean -P yass.gpr
      - cd obj
      - adactl -f ../others/rules.aru -p ../yass.gpr ../src/$1
   description: Run AdaControl to check correctness of the selected file
   flags:
      - unixpath
