- command:
   name: runtests
   execute:
      - cd tests/driver
      - ./test_runner
   description: Run Yass unit tests
- command:
   name: debug
   execute:
      - gprbuild -P yass.gpr
   description: Build Yass in debug mode
- command:
   name: release
   execute:
      - tclsh others/build.tcl
   description: Build yass in release mode
- command:
   name: analyze
   execute:
      - gprbuild -P yass.gpr -XMode=analyze
   description: Build yass in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P yass.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P yass.gpr
   description: Regenerate unit tests
- command:
   name: tests
   execute:
      - gprbuild -P tests/driver/test_driver.gpr
   description: Build yass unit tests
- command:
   name: docs
   execute:
      - others/generatedocs.tcl
   description: Generate code documentation
- command:
   name: gprof
   execute:
      - gprof bin/yass gmon.out
   description: Generate gprof report
- command:
   name: push
   execute:
      - fossil push
      - fossil git export --force
   description: Update remote Fossil repository and its Git mirror
