name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild:10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate tests
      run: gnattest -P yass.gpr

    - name: Build the tests
      run: gprbuild -P tests/driver/test_driver.gpr

    - name: Run the tests
      run: others/tests.tcl

  adacontrol:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adacontrol:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run AdaControl
      run: |
         mkdir obj
         cd obj
         adactl -f ../others/rules.aru -p ../yass.gpr -o ../adacontrol.log -r yass-aws-templates_parser-dom-unicode-input_sources-aws_config-aws_net_log
         cd ..

    - name: Upload the log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
         name: adacontrol.log
         path: adacontrol.log

  build_linux:

    needs: adacontrol

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild:10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl x86_64-linux-gnu

    - name: Compress the artifact
      run: tar -cf yass-development-linux.tar usr

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: yass-development-linux.tar
         path: yass-development-linux.tar

  build_windows:

    needs: adacontrol

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuildwin64:10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl x86_64-windows

    - name: Compress the artifact
      run: tar -cf yass-development-windows.tar release

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: yass-development-windows.tar
         path: yass-development-windows.tar
